:toc:

== Design Detail of `commandunit`

=== The wrapper script

The `commandunit` comes with a "wrapper" script that defines a bash function for you.
The function automatically downloads the specified version of `commandunit` from its repo and execute it.

It has two classes of options, which are "wrapper" options and normal options.
The former controls the behavior of the wrapper and the latter controls the `commandunit` self's behavior.

For instance, you can specify a version of `commandunit` 's main part by `--version=...`, which is one of wrapper options.
To specify tests to be executed by a regular expression you can ue `--filter=...` option which is a normal option.

=== Key Elements

Technical Elements::
- Docker
- bash
- jq-front
- Preprocessing pipeline
- "wrapper" module
- native mode
- pipeline

Dependencies::
- jq-front

It uses `jq-front` to

=== Directory Layout

The default directory layout of `commandunit`-based project is designed to be compatible with Maven-based project<<maven-designDetail>>.

[source]
.Default Directory Layout
----
src/                                    <1>
  main/
  test/                                 <2>
    .commandunit/                       <3>
      jsonpp/
      testdrivers/
    scripts/
target/
  commandunit/
    report/                             <4>
    work/                               <5>
      scripts/
        core/
          {testcase-1}.json
          {testcase-1}.json++
          {testcase-1}.yaml++
----
<1> Current directory
<2> A directory to store test scripts. (test script directory, can be changed through `--test-srcdir=` option)
<3> A directory to store `commandunit` 's configuration. (test project configuration directory)
exported as COMMANDUNIT_DIR environment variable.
<4> A directory to which `commandunit` writes report.
(report directory, can be changed through `--test-reportdir=` option)
<5> A directory to which `commandunit` stores processed test scripts and intermediate files. (working directory, can be changed through `--test-workdir` option)


=== `commandunit` 's Pipeline

The following diagram illustrates data flows of the `commandunit`.

include::resources/diagrams/pipeline.adoc[]

2.1 `preprocess` subcommand:: This step converts test case definitions into JSON files, which can be executed by the step that comes the next: `run` step.
2.2 `run` subcommand:: This step runs the test case definitions.
Test result is accumulated in Result Repository
2.3 `report` subcommand:: A step to compile human readable report from the output of the previous step (`run`).

Compiled Test Repository:: (t.b.d.) `--test-srcdir`
Result Repository:: `testreport.json` (t.b.d.) / default (directory in the "standard" directory structure) `--test-reportdir`
Test Report:: `testreport.adoc`

wrapper
native mode

ignore-mtime

[bibliography]
== References

- [[[maven-designDetail, 1]]] Apache Maven Project https://maven.apache.org/[Apache Maven Project]: 2002-2022


[.text-right]
// suppress inspection "AsciiDocLinkResolve"
link:index.html[top]