:toc:

== Design Concept of `commandunit`

=== YAML, not Gherkin

Gherkin is one notation widely used in "Cucumber"'s ecosystem.

[source, gherkin]
.A Gherkin (Cucumber) Example
----
Feature: Guess the word

  # The first example has two steps
  Scenario: Maker starts a game
    When the Maker starts a game
    Then the Maker waits for a Breaker to join

  # The second example has three steps
  Scenario: Breaker joins a game
    Given the Maker has started a game with the word "silky"
    When the Breaker joins the Maker's game
    Then the Breaker must guess a word with 5 characters
----

If we write this in YAML, it will be like this:


[source, yaml]
.YAML version of Gherkin Example
----
---
Feature:
  Name: Guess the word <1>
  Scenarios:
  # The first example has two steps
  - Name: Maker starts a game
    When: the Maker starts a game
    Then: the Maker waits for a Breaker to join
  # The second example has three steps
  - Name: Breaker joins a game <1>
    Given: the Maker has started a game with the word "silky"
    When: the Breaker joins the Maker's game
    Then: the Breaker must guess a word with 5 characters
----
<1>: These attributes are introduced to define names of a feature and a scenario, which is defined without explicit attribute name in Gherkin.

Gherkin seems slightly simpler and cleaner since you will need fewer keywords, however, is it really worth adapting a dedicated notation not used anything but it?
By using Gherkin, you will need a set of plugins to support Gherkin for every tool used in a software development project such as browser, editor, or IDE.

If so, wouldn't YAML be good enough to define your test cases?
isn't YAML good enough, if we have a way to avoid repeating the same thing over and over again?

`yaml{plus}{plus}` -> `json{plus}{plus}` -> `json` -> execute test
(plus)
YAML, JSON, JSON++

Given, when, then

Separating concerns

== References

include::_references.adoc[]

[.text-right]
// suppress inspection "AsciiDocLinkResolve"
link:index.html[top]
