// suppress inspection "CucumberUndefinedStep" for whole file
:toc:

installation.adoc:: Installation Manual
concept.adoc:: Design Concept
design.adoc:: Design Detail
userManual.adoc:: UserManual
userManual-ProgrammingManual.adoc:: ProgrammingManual


== Introduction and QuickStart

`commandunit` is a test tool for your UNIX-based CLI tools powered by `jq-front`[<<jq-front>>].
To try it, clone `commandunit-example` repo (or `example` branch? t.b.d.)
And run it.


(t.b.d.)


== Design Concept

Test definitions are repetitive.
But any single test is not (should not be) identical to any other one.
In generic programming languages have features, we can address it with their features such  user define functions, data types, inheritance, and others.

Gherkin is one notation widely used in "Cucumber"'s ecosystem.

[source, gherkin]
.A Gherkin (Cucumber) Example
----
Feature: Guess the word

  # The first example has two steps
  Scenario: Maker starts a game
    When the Maker starts a game
    Then the Maker waits for a Breaker to join

  # The second example has three steps
  Scenario: Breaker joins a game
    Given the Maker has started a game with the word "silky"
    When the Breaker joins the Maker's game
    Then the Breaker must guess a word with 5 characters
----
From https://cucumber.io/docs/gherkin/reference/

If we write this in YAML, it will be like this:


[source, yaml]
.YAML version of Gherkin Example
----
---
Feature:
  Name: Guess the word <1>
  Scenarios:
  # The first example has two steps
  - Name: Maker starts a game
    When: the Maker starts a game
    Then: the Maker waits for a Breaker to join
  # The second example has three steps
  - Name: Breaker joins a game <1>
    Given: the Maker has started a game with the word "silky"
    When: the Breaker joins the Maker's game
    Then: the Breaker must guess a word with 5 characters
----
<1> Introduced to define names of a feature and a scenario, which is defined without explicit attribute name in Gherkin.

Isn't YAML good enough, if we have a way to avoid repeating the same thing over and over again?

`yaml{plus}{plus}` -> `json{plus}{plus}` -> `json` -> execute test
(plus)
YAML, JSON, JSON++

Given, when, then

Separating concerns


== Design Detail

The data flow diagram.

Technical Elements::
- Docker
- jq-front
- Preprocessing pipeline

Dependencies
- jq-front

Tested with:

== System Requirements

=== On Linux
Dockerized version::
- Distribution: Ubuntu 22.04
- dockerd: ???

"native" version::
- `jq-front` (`0.54`, Dockerized)
- `jq` (`jq-1.5-1-a5b5cbe` or later)
- `yaml2json` (`0.3.0`, installed through `npm install yamljs`)

=== On macOS
Dockerized version::
- `docker`: Docker version 23.0.5, build bc4487a (macOS)
- `dockerd`: Docker Desktop 4.19.0 (106363)

"native" version::
- `jq-front` (`0.54`, Dockerized)
- `jq` (`jq-1.6`)
- `yaml2json` (`0.3.0`, installed through `npm install yamljs`)


== User Manual

(t.b.d.)

=== Command-line Manual

(t.b.d.)

options

"native" mode

=== Installation Manual

The wrapper script.
- Docker version
- Native version

One-liner.
(t.b.d.)

=== Programming Manual

Directory structure
Environment variables

Syntax::
  Given, When, Then,


Execution::
  subcommands:: preprocess, run, report, none

built-in libraries

`base/normal.json`:: (t.b.d.)
`bud/lib/core.rc`:: (t.b.d.)


=== Tips

`none` subcommand.

macOS `yaml2json` doesn't work.


== Walking Through Examples

(t.b.d.)

== FAQ

(t.b.d.)

if macOS `yaml2json` doesn't work. -> Workaround

`/opt/homebrew/bin/yaml2json` `0.3.0`[<<jq-front>>]


=== References

- [[jq-front, 1]] jq-front project in github.org. https://github.com/dakusui/jq-front[jq-front]: 2019
- [[Cfront, 2]] Cfront article in en.wikipedia.org. https://en.wikipedia.org/wiki/Cfront[Cfront]:
2019
- [[power-assert, 3]] power-assert https://github.com/power-assert-js/power-assert[power-assert]: 2021
